### ISSUE TITLE
Mudança de status de venda agenciada para em aberto

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/app-bling-erp#1]
Segundo lojistas, não existe parâmetro de venda aprovada, é possível criar isso no Bling, mas muitos não usam. Pelo que conversei com lojistas, normalmente é enviado só pedido aprovado, se for cancelado, atualiza para cancelado. Porque todos os marketplaces fazem isso, entao é um fluxo normal. Se cai pedido aguardando pagamento, teria que fazer reserva de estoque e enviar pro Bling essa reserva de estoque. Porque quem normalmente tira nota fiscal, nem olha status, se cai no Bling, já retira nota e dá sequencia.
@leomp12

**Comment by leomp12** [comment]
Eu não entendi foi nada haha
Qual é o TODO aqui? Pelo texto achei que queria enviar pedidos só quando aprovados, mas tem uma opção pra isto (na 1011 não aparece porque a instalação está desatualizada), mas o título do issue não tem nada a ver com isso...

**Comment by leomp12** [comment]
E não sei se tem a ver porque realmente não entendi, mas vai como "venda agenciada" quando não foi enviado mas foi pago, quando o pagamento está pendente vai "em aberto", se já enviado vai "atendido", acho que isto é o padrão correto.

**Comment by matheusgnreis** [comment]
Seguinte, o fluxo normal do Bling para todas integrações (segundo 4 lojas) é entrar pedido aprovado apenas, para que seja colocado em separação, depois emitir a nota e ir automaticamente para atendido.  Então, segundo eles não querem que o pedido aprovado vá como **Venda Agenciada** e sim **Em aberto**. Pois todos os pedidos do bling teoricamente são aprovados.

Quando há pedido como boleto ou cartão que fica em análise, deveria ser feito uma reserva de estoque e enviada para o Bling, pra evitar que tenha um gap de estoque, se aprovado envia o pedido, se não for aprovado, desconsidera.

Há um tempo, quando conversei com o pessoal do Bling, eles indicaram enviar somente pedidos aprovados, pois todas integrações que eles têm fazem isso, por isso nunca consideraram colocar por padrão um status aprovado. 

Hoje existe a possibilidade de criar novos status, como aprovado e entregue, alguns fazem isso, principalmente entregue, por causa de outras integrações que dependem disso.

**Comment by leomp12** [comment]
OK, então essa "venda agenciada" significa o quê afinal? Em qual cenário usa isso?
