### ISSUE TITLE
O callback de estoque não foi concluído corretamente.

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/app-bling-erp#14]
Alguns lojistas que possuem um volume maior de pedidos recebem constantemente que o callback de pedidos e estoque não estão sendo concluídos corretamente, a resposta é sempre:

Error: could not handle the request

**Comment by matheusgnreis** [comment]
Detalhe é que os pedidos que verifiquei e estoques, o status veio, porém veio uma alteração com status que já tinha. 

Não sei, se quando tem o status já o callback é ignorado. Por exemplo, quando o lojista coloca em Enviado pela plataforma, no Bling vai para atendido e dai tem o retorno de callback com nota emitida, sendo que já em algum momento esteve com a nota emitida já. Nesses casos, já solicitei para criar uma transição para outro status quando recebesse a informação `enviado`, então não sei se é exatamente isso, só colocando um ponto que observei para ver se depois faz sentido.

De estoque já me informaram um que na plataforma o estoque estava igual, mas receberam o email.

**Comment by leomp12** [comment]
Do estoque provavelmente teve retentativa e atualizou normal.

Do pedido não sei se entendi o que você aconteceu e o que você quer, mas ele só vai ignorar o callback todo se a situação do Bling não alterar, se houver alguma mudança na situação no Bling ele vai verificar NF, código de rastreio e status, aí ele verifique se não está salvo na plataforma e salva as alterações parciais no pedido.

**Comment by matheusgnreis** [comment]
Se essas informações já estiverem salvas na plataforma, após mudar status de novo, ele ignora?
Se ignorar, talvez poderia colocar uma resposta positiva pro Bling, se não o Bling entende que não deu certo e ai envia email pro lojista e se der 10 vezes isso, ele desabilita o callback

**Comment by leomp12** [comment]
@matheusgnreis eu acho que c tá misturando as coisas aí e não tô entendendo, você tá falando de callbacks de pedidos ou produtos?

Sempre retorna status OK pro Bling, inclusive esse processo não é síncrono, só adiciona o pedido na fila e finaliza a request do Bling, depois é que esse pedido vai ser processado na fila, ignorando ou alterando na plataforma...

O erro com o callback de estoque aí é outro, acho que tem algo quebrando a função em alguns casos, aí retorna esse erro pro Bling, nada a ver também com estar atualizado ou não na plataforma.

**Comment by matheusgnreis** [comment]
Esse erro Error: could not handle the request está rolando tanto para callback de estoque, quanto para pedido pelos emails que me foi enviado

**Comment by leomp12** [comment]
Não estou encontrando erro no callback no Bling, então acho que pelo menos não parece frequente, resolvi uns outros mas nada relacionado a isso.
Sei que de vez em quando o Firestore quebra e daria esse erro, principalmente se tiver um volume maior de requisições, mas é bem raro e nesse caso o correto seria mesmo retornar erro para o Bling enviar uma retentativa do callback.
Tá chegando a desativar o callback nessas lojas aí ou só incomodando por e-mail de vez em quando?

**Comment by matheusgnreis** [comment]
Desabilita esporadicamente, talvez só quando tem muitos erros de uma vez. Acho que desde a reclamação que já deve ter 1 mês, desabilitou só quando abri o issue
