### ISSUE TITLE
Envio errado de produto no pedido

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/app-bling-erp#22]
O pedido https://app.e-com.plus/#/resources/orders/6043b4286d50911b60560894 entrou com sku ```"sku\":\"150350_Sarja_Preta_GG\"```, conforme dá pra ser visto no log **80570** da loja e assim ficou dentro do pedido na plataforma, porém no bling subiu como **150350_Sarja_Preta_G**, de acordo com o corpo:

`
#1035 {"numero_loja":"1800","data":"06/03/2021","numero":"1800","loja":203419468,"cliente":{"nome":"PAULO XXX","tipoPessoa":"F","cpf_cnpj":"xxx","email":"xxx@ymail.com","celular":"XXX","endereco":"xxx","numero":"1277","complemento":"LOJA","bairro":"CENTRO","cep":"00.600-000","cidade":"São Joaquim da Barra","uf":"SP"},"itens":[{"item":{"codigo":"150350_Sarja_Preta_G","descricao":"Camisa Sarja Masculina Preta Manga Curta / GG","un":"Un","qtde":1,"vlr_unit":79.9}}],"parcelas":[{"parcela":{"data":"06/03/2021","vlr":89.29,"obs":"Pagar com Pix (1/1)"}}],"transporte":{"transportadora":"Correios","servico_correios":"SEDEX","peso_bruto":0.00035,"dados_etiqueta":{"nome":"PAULO XXXX","endereco":"XX","numero":"XXX","complemento":"LOJA","bairro":"CENTRO","cep":"00.600-000","municipio":"São Joaquim da Barra","uf":"SP"}},"vlr_frete":15.78,"vlr_desconto":6.39}
`

**Comment by leomp12** [comment]
Estava limitando o SKU a 20 chars, talvez eu li errado na referência do Bling...
