### ISSUE TITLE
Unhandled rejection 

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/app-bling-erp#25]
Alguns pedidos não estão sendo enviados ao Bling de forma automática, peguei um exemplo no log:

7:45:16.233 AM
	
	
app
> Webhook #1162 60420b586d50911b6054e2d7 [orders]
	
7:45:16.233 AM
	
	
app

> Starting #1162 _exportation/order_ids/60420b586d50911b6054e2d7 

	
7:45:16.341 AM
	
	
app
Function execution took 556 ms, finished with status code: 202
	
7:45:17.406 AM
	
	
app
Unhandled rejection 

Essa foi uma segunda tentativa e mesmo assim o Bling não aceitou o pedido e assim, ficou perdido no meio dos pedidos do cliente, que acabou sendo acionado por receber um pedido e não enviar ao cliente.

Quando clico pra filtrar vejo só isso
labels.execution_id = "txrepbw2z5k6" (primeira tentativa)
labels.execution_id = "txrelhgzbbyx" (segunda tentativa)

**Comment by leomp12** [comment]
E esse pedido é de qual loja?

**Comment by matheusgnreis** [comment]
Pedido 60420b586d50911b6054e2d7, loja 1162, segundo o lojista ele tem outros, mas não me informou ainda. Esse problema foi para criar. Mas acabei de receber um outro da loja 1035 (pedido 60516cbda735d032cbbd35f6), que o webhook apareceu lá no log, mas não veio o status do pedido com nota fiscal

**Comment by leomp12** [comment]
@matheusgnreis você tem que olhar o log abaixo do `Unhandled rejection`, até pouco tempo atrás dava bastante o erro:

```console
Error: Bling error code NaN for [put] /produtoLoja/203588743/XBC5890/json/
    at instance.then.response (/workspace/lib/bling/constructor.js:27:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Inclusive no dia 05/03 (dia do pedido) no horário que você mencionou foi o que ocorreu, mas não tem nada a ver com exportação de pedido, só se isso de alguma forma atrapalhou a fila, salvou incorretamente depois ou algo do tipo.

> Mas acabei de receber um outro da loja 1035 (pedido 60516cbda735d032cbbd35f6), que o webhook apareceu lá no log, mas não veio o status do pedido com nota fiscal

Nada a ver com o resto, na verdade não tenho certeza se entendi também, fato é que nem todo callback do Bling será processado, bater em log que recebeu o callback não significa que vai alterar o pedido na plataforma, no mínimo tem que certificar que esse pedido teve o status alterado no Bling, então ver se foi pra fila e se tem outros logs pelo número, nesse caso se parecer errado você pode abrir outro issue explicando um pouco melhor por favor.

**Comment by leomp12** [comment]
Esse pedido `60420b586d50911b6054e2d7` acredito que foi ignorado por causa do status, não deu erro por causa dele (a rejeição que você mencionou não tem relação, era outra execução em paralelo), nem salvou nada no log do app, ele já entrou aprovado, talvez ainda não estava no `financial_status` no webhook e o app está configurado para passar apenas os aprovados.

**Comment by leomp12** [comment]
Vou fechar o issue com um commit, se achar outro pedido que não foi criado no dia/hora certo e que não tenha entrado aprovado direto abre de novo por favor mencionando esse outro pedido.
