### ISSUE TITLE
Atualização no Bling por alteração de preço na e-com

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/app-bling-erp#27]
Ocorreu o webhook, conforme podemos ver aqui:

18 de mar. de 2021
12:33:22.682 PM app
> Webhook #1225 603852139332dd6865df4a8b [products]
12:33:22.682 PM app
> Starting #1225 _exportation/product_ids/603852139332dd6865df4a8b

Porém não surtiu efeito no Bling. Tenho a conta da cliente aqui do Bling, esperei meia hora, mas não teve resposta.

Ela me indicou outros produtos para olhar também

**Comment by leomp12** [comment]
Conforme podemos ver o quê? 😄 
No que você colou aí não tem erro nenhum, pesquisou em log mais registros pelo ID do produto e/ou SKU?

**Comment by matheusgnreis** [comment]
Teve o entendimento da alteração do preço e envio pra exportação. Mas não chegou lá. Pesquisei pelo ID (mostrou o que enviei acima) e sku (teve a importação dia 16, ultima movimentação).
Vou tentar exportar manualmente pra ver

**Comment by matheusgnreis** [comment]
Exportando manualmente, dá certo. 

![Screenshot_2021-03-18 ecom-bling – Console do Firebase](https://user-images.githubusercontent.com/35343551/111665458-86996500-87f1-11eb-8a9d-075364d2fe3b.png)

Até aparece aqui que a fila está zerada.

Mas pela sincronização de preço vai pra fila, mas não mostra que está zerada e não há alteração do produto no Bling

![Screenshot_2021-03-18 ecom-bling – Console do Firebase(1)](https://user-images.githubusercontent.com/35343551/111665596-a6c92400-87f1-11eb-889d-a1fa47d68fc1.png)
Desci sem filtro pra acompanhar e não mostra a fila zerada

**Comment by leomp12** [comment]
Na verdade isso aí da fila zerar não significa sucesso ou erro, esse 202 com o log é só quando a fila tá salva no data do app, nos webhooks nunca vai dar isso mesmo.

**Comment by leomp12** [comment]
Qual é o SKU desse produto?
Tem uns erros hoje tipo esse aí:

```console
Error: Bling error {"123":"O produto com este código não foi encontrado no sistema"} for [put] /produtoLoja/203596641/8331290-759-5/json/
    at instance.then.response (/workspace/lib/bling/constructor.js:32:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Isso aí é justamente para atualizar o preço do produto, e aconteceria se o Bling encontrar o tal produto pelo SKU e ele estiver associado a uma loja (com o tal `produtoLoja`) diferente da configurada no app.

> Ou talvez até esteja associado a loja configurada no app (`203596641` nesse caso) e mesmo assim o Bling tá dando esse erro (não duvido também).

**Comment by leomp12** [comment]
Detalhe é que a resposta de erro no Bling geralmente é um array `erros[0].erro`, tá documentado dessa forma também, mas nesse caso aí é um objeto 😐 
Cada dia é uma "boa prática" nova que a gente descobre, paciência né...

**Comment by matheusgnreis** [comment]
8333261

Provavelmente o produtoLoja é diferente, porque já existia esses produtos no Bling e vieram de importação, então ele já era do padrão do Bling lá.

Edit: Fiz um get no produto e não tinha esse atributo produtoLoja

**Comment by leomp12** [comment]
Mas já que ele tá associado a outra loja ou loja nenhuma, na plataforma o app está configurado com código de loja? Se sim, o GET que você fez foi com o parâmetro `loja=${blingStore}`?

**Comment by matheusgnreis** [comment]
Fiz ele com e sem, dá o mesmo resultado, inclusive coloquei 0000 no bling store (https://bling.com.br/Api/v2/produto/8333261/json/?loja=0000&apikey=xxx) e deu mesma coisa. Acho que se tiver um produto na loja, ele retorna da loja, se não tiver, mostra do mesmo jeito

**Comment by leomp12** [comment]
Tem um `produtoLoja` sim uai:

```json
"produtoLoja": {
    "idProdutoLoja": "603852139332dd6865df4a8b",
    "preco": {
        "preco": 1.7,
        "precoPromocional": 1.35
    },
    "dataInclusao": "2021-03-10",
    "dataAlteracao": "2021-03-18"
},
```

E acabei de fazer um teste e foi alterado o preço:

```json
"produtoLoja": {
  "idProdutoLoja": "603852139332dd6865df4a8b",
  "preco": {
    "preco": 1.71,
    "precoPromocional": 1.35
  },
  "dataInclusao": "2021-03-10",
  "dataAlteracao": "2021-03-18"
},
```

Pelo jeito acho que desde o início foi certo haha
Mas manteve o `precoPromocional`, nesse produto aí não tem promoção então mandamos um [PUT pro Bling só com o `{ preco }`](https://github.com/ecomplus/app-bling-erp/blob/master/functions/lib/integration/export-product.js#L77-L79), achei que nesse caso ele resetaria o `precoPromocional`, ficaria sem (sendo um PUT é o que deveria ocorrer), mas pelo jeito não. Nesse caso não sei como remover o field, não vi nada na documentação deles, então até está atualizando o preço de venda certinho, problema é que manteve esse promocional 1.35.

**Comment by leomp12** [comment]
Já voltei pra `1.7` e já fiz a requisição no Bling de novo, atualizou novamente, mas segue o `precoPromocional` com valor antigo, se puder ver com eles como faz pra remover isso no PUT, talvez mandar zero (gambiarra)?

**Comment by matheusgnreis** [comment]
Beleza, vou olhar. No painel do Bling não dá pra ver dentro do produto o preço promocional, de forma fácil, precisa ir em outro lugar pra mexer nisso. Vou entrar em contato com eles para saber.

**Comment by matheusgnreis** [comment]
Talvez seja mais fácil mandar igual os preços se não tiver preço promocional na plataforma

**Comment by leomp12** [comment]
Resolve gambiarra com gambiarra né 😬
