### ISSUE TITLE
Importar Códigos de Rastreio

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/app-bling-erp#4]
Segundo o Bling, existem duas formas de importar código de rastreio, quando há alteração de pedido e ele já está dentro do pedido, conforme o corpo abaixo:

{"retorno":{"pedidos":[{"pedido":{"desconto":"0,00","observacoes":"Confirmo pedido de camiseta na cor cinza","observacaointerna":"","data":"2020-12-08","numero":"5398","numeroOrdemCompra":"","vendedor":"John Robert Hoffmann","valorfrete":"0.00","totalprodutos":"140.00","totalvenda":"140.00","situacao":"Atendido","loja":"203168377","numeroPedidoLoja":"5398","tipoIntegracao":"Api","cliente":{"id":"10486197519","nome":"Eli Magno Faleiros","cnpj":"XXX.XXX.XXX-XX","ie":"","rg":"","endereco":"Rua Floriano Peixoto","numero":"1560","complemento":"apto  81","cidade":"Franca","bairro":"Centro","cep":"14.400-760","uf":"SP","email":"elimagnoXXX@hotmail.com","celular":"16999993786","fone":"31999999999"},"pagamento":{"categoria":"SITE"},"nota":{"serie":"2","numero":"000149","dataEmissao":"2020-12-09 13:47:02","situacao":"7","valorNota":"140.00","chaveAcesso":"00001200527306000109550020000001491996792554"},"transporte":{"transportadora":"MIOR TRANSPORTES LTDA","cnpj":"05.756.860\/0001-73","tipo_frete":"R","qtde_volumes":"1","enderecoEntrega":{"nome":"Eli Magno Faleiros","endereco":"Rua Floriano Peixoto","numero":"10","complemento":"apto  81","cidade":"Franca","bairro":"Centro","cep":"14.400-760","uf":"SP"},"volumes":[{"volume":{"id":"10499665973","idServico":"10226330878","idOrigem":"10486197530","servico":"JADLOG","codigoServico":"3","codigoRastreamento":"","valorFretePrevisto":"0.00","remessa":null,"dataSaida":"","prazoEntregaPrevisto":"","valorDeclarado":"0.00","avisoRecebimento":false,"maoPropria":false,"dimensoes":{"peso":"0.210","altura":"0","largura":"0","comprimento":"0","diametro":"0"},"urlRastreamento":"www2.correios.com.br\/sistemas\/rastreamento\/"}}],"servico_correios":"JADLOG"},"itens":[{"item":{"codigo":"001082GG000021","descricao":"CAMISETA MASCULINA ZIPER Cor:MESCLA;Tamanho 1:GG","quantidade":"1.0000","valorunidade":"140.0000000000","precocusto":"52.5000000000","descontoItem":"0.00","un":"un","pesoBruto":"0.21000","largura":"2cm","altura":"21cm","profundidade":"29.7cm","descricaoDetalhada":"","unidadeMedida":"cm","gtin":"7898427180039"}}],"parcelas":[{"parcela":{"idLancamento":"0","valor":"140.00","dataVencimento":"2020-12-08 00:00:00","obs":"Cart\u00e3o de cr\u00e9dito (1\/1)","destino":"1","forma_pagamento":{"id":"1310089","descricao":"Pagar.me","codigoFiscal":"3","bandeira":"1"}}}],"codigosRastreamento":{"codigoRastreamento":""}}}]}}

```
https://bling.com.br/Api/v2/pedido/5398/json/?apikey=xxxx
```

Já da nota fiscal está aqui um exemplo
https://ajuda.bling.com.br/hc/pt-br/articles/360046379674-GET-notafiscal-numero-serie-

**Comment by leomp12** [comment]
Uai mas o JSON de exemplo aqui não tem código de rastreio em lugar nenhum @matheusgnreis , só tem o URL genérico da página de rastreio dos Correios.

**Comment by leomp12** [comment]
E chatão bater a tal nota fiscal pra pegar código de rastreio em :neutral_face:

**Comment by matheusgnreis** [comment]
Coloquei o errado haha. Vou pegar o certo, estava tentando pegar um que tinha com correios e um que Nao tinha. Coloquei o que não tinha
