### ISSUE TITLE
Erro de atualização de estoque

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/app-bling-erp#42]
Produto não foi encontrado para atualizar o estoque, gerando o seguinte erro:

9:08:45.550 AM | &nbsp;
-- | --

&nbsp; | app       &gt; Bling callback: #1035 150350_Sarja_Vinho_GG =&gt; 0 | &nbsp;
-- | -- | --

<div ng-repeat="log in controller.logs" class="f7s-log-row"><functions-log-row ng-if="::!log.isDateHeader" log="log" extension-name="::controller.getExtensionName(log)">
&nbsp;
--

 </functions-log-row> </div><div ng-repeat="log in controller.logs" class="f7s-log-row">  <functions-log-row ng-if="::!log.isDateHeader" log="log" extension-name="::controller.getExtensionName(log)"> 
9:08:46.825 AM | &nbsp;
-- | --

</functions-log-row></div>
&nbsp; | app       #1035 skipping 150350_Sarja_Vinho_GG / undefined
-- | --

https://github.com/ecomplus/app-bling-erp/blob/master/functions/lib/integration/import-product.js#L133

**Comment by leomp12** [comment]
Não seria um erro do app o produto não ser encontrado, ou o SKU estava incorreto ou houve algo de errado na API de busca na ocasião.

Buscando pelo SKU nos logs do Firebase dá pra ver que o log que você colou aqui é de 15 de maio, já faz bastante tempo, só varrendo logs da API pra conferir se o SKU da variação já bateria certinho nessa data.

Hoje é fácil verificar que o SKU bate, mas de fato o mesmo callback hoje funcionou normalmente:

![Screenshot_2021-06-01 ecom-bling – Console do Firebase](https://user-images.githubusercontent.com/10326572/120335919-42821080-c2c8-11eb-91a8-000809470078.png)
