### ISSUE TITLE
Enfileirar eventos de callbacks do Bling

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/app-bling-erp#47]
Algumas lojas estão perdendo sincronização com o Bling, pois está desativando pelo callback. Então segundo o que informaram no ticket, eles querem ter nossa resposta 200, independente de qualquer coisa, para saber que a notificação chegou.

**Comment by leomp12** [comment]
Na verdade o enhancement é enfileirar os eventos do Bling e ao mesmo tempo tentar processar assíncrono (pra evitar delay), mas isso é meio chato. Só retornar 200 é mole, mas fica muito mais suscetível a perder eventos.

> Quando há resposta de erro a intenção é que exista uma retentativa, é esperado que o webhook seja enviado de novo alguns segundos depois, pelo menos é assim que funcionam sistemas de webhooks quando bem implementados.

**Comment by matheusgnreis** [comment]
Eles que sugeriram enviar, informei eles que poderia ser ruim, porque não significaria que tivessem de fato uma alteração, mas eles não ligam muito pra isso, por isso sugeri igual eles falaram. Valeu.

**Comment by leomp12** [comment]
Uai acho que eles só querem tirar o deles fora né haha

Em ter., 15 de jun. de 2021 23:59, Matheus Reis ***@***.***>
escreveu:

**Comment by leomp12** [comment]
Não está sendo enfileirado mas já está retornando sempre 200 e tratando retentativas internamente. Parece suficiente por enquanto.
