### ISSUE TITLE
Buscar estoque do depósito

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/app-bling-erp#49]
Se na configuração do app estiver configurado um depósito, buscar o estoque do depósito.

```
{
    "retorno": {
        "estoques": [
            {
                "estoque": {
                    "id": "12345",
                    "codigo": "prod",
                    "nome": "Produto",
                    "estoqueAtual": 2,
                    "depositos": [
                        {
                            "deposito": {
                                "id": "1234561",
                                "nome": "Deposito 1",
                                "saldo": "3.00",
                                "desconsiderar": "N"
                                "saldoVirtual": 2
                            }
                        },
                        {
                            "deposito": {
                                "id": "1234562",
                                "nome": "Deposito 2 (desconsidera o saldo)",
                                "saldo": 0,
                                "desconsiderar": "S"
                                "saldoVirtual": -1
                            }
                        }
                    ]
                }
            }
        ]
    }
}
```

Solicitação do grupo customic para trabalho com depósitos diferentes

**Comment by matheusgnreis** [comment]
@leomp12 o callback sem o deposito funcionou, com o depósito aparentemente não. Tem como colocar mais informações no log? No bling da loja eu consigo ver que no deposito x tem 0 unidades e no geral tem 1, na plataforma continuou mostrando 1

**Comment by leomp12** [comment]
Estranho, me baseei no JSON do exemplo aí, mas não sei realmente se é assim que chega pra nós não

**Comment by matheusgnreis** [comment]
```{"id":"13075155071","codigo":"301624","nome":"Ajustável Popsockets  Stretch Black Kicks Bk Suporte Celular","estoqueAtual":2,"depositos":[{"deposito":{"id":"9585657589","nome":"Geral","saldo":"2.0000000000","desconsiderar":"N","saldoVirtual":"2.0000000000"}},{"deposito":{"id":"12126693967","nome":"ML FULL","saldo":"2.0000000000","desconsiderar":"S","saldoVirtual":"2.0000000000"}},{"deposito":{"id":"12432325131","nome":"FBA Onsite","saldo":"2.0000000000","desconsiderar":"S","saldoVirtual":"2.0000000000"}},{"deposito":{"id":"13372451803","nome":"PIER SP","saldo":0,"desconsiderar":"N","saldoVirtual":0}},{"deposito":{"id":"13445292920","nome":"PIER ES","saldo":0,"desconsiderar":"N","saldoVirtual":0}}]} ```

O callback até veio certo, mas a informação não. O que inseri no painel é 13445292920 e deveria editar pra 0

**Comment by leomp12** [comment]
Qual loja? Qual é o ID do produto?

**Comment by matheusgnreis** [comment]
60ca1155641ad82fcc29f46e e 1162

**Comment by leomp12** [comment]
@matheusgnreis 

```console
#1162 /products/60ca1155641ad82fcc29f46e/quantity.json { quantity: 0 }
```

Era isso?

**Comment by matheusgnreis** [comment]
Agora sim, fiz um novo teste e veio, após a alteração ai

**Comment by leomp12** [comment]
Beleza, valeu
