### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by leomp12** [ecomplus/app-bling-erp#5]
A documentação ainda ficou sem falar do "Código da loja no Bling", acho que isto é importante.
A parte sobre status de pedido acho que está errada (ou só incompleta) e a instrução que consta sobre reserva de estoque não sei se é válida, acho que isto vai depender da operação da loja no ERP, não tem ligação específica com a integração...

**Comment by leomp12** [comment]
@matheusgnreis ou @ThaisChaves alguém dá uma revisada por favor quando possível :+1:

**Comment by leomp12** [comment]
Acho que algumas imagens no tutorial também ficaram excessivamente grandes, atrapalha um pouco a leitura, aconteceu o mesmo com o do Opiniões Verificadas, em vez de usar markup de MD pra inserir a imagem pode ser o caso de usar HTML mesmo `<img src="..." style="max-height: ...">` e setar a altura ou largura máxima dessas imagens (deve variar de uma pra outra, se não a gente podia até fazer com CSS de forma genérica).

**Comment by leomp12** [comment]
Também não usamos callback de nota fiscal, pegamos a nota fiscal mas quando há uma alteração de situação (status) do pedido, então seria bom fixar isso no print respectivo nesse tutorial.

**Comment by leomp12** [comment]
Como ficou isso aqui pessoal @matheusgnreis @ThaisChaves ?

**Comment by matheusgnreis** [comment]
@leomp12 atualizei o tutorial do bling com os topicos solicitados pela homolocagao do bling https://github.com/ecomplus/app-bling-erp/pull/32
