### ISSUE TITLE
Erro na importação de status do pedido

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/app-bling-erp#57]
**Descreva o erro**
O status do pedido foi alterado no bling, o mesmo chegou na plataforma, pois temos no log:

10:05:35.929 AM 
> Starting #1077 ___importation/order_numbers/6047 

Até encontrou o pedido:

10:05:37.253 AM 

#1077 found order 6047 

Mas o status não foi alterado.

Não mostra nenhum erro posterior, ao filtrar por esse evento:

![Screenshot 2021-08-24 at 10-30-49 ecom-bling – Console do Firebase](https://user-images.githubusercontent.com/35343551/130625440-6ca2c7a3-9ffc-4aac-9c08-752e85acbc35.png)

**Comment by leomp12** [comment]
O `found order` nesse trecho não tem relação com o callback do Bling, são
execuções diferentes.
Você buscou nos logs pelo número do pedido?

Em ter., 24 de ago. de 2021 10:32, Matheus Reis ***@***.***>
escreveu:

**Comment by leomp12** [comment]
Aliás, pelo número e depois pelo ID do pedido?

Em ter., 24 de ago. de 2021 10:38, Leonardo Matos ***@***.***>
escreveu:

**Comment by leomp12** [comment]
Nesse momento que você mencionou o status que tínhamos do Bling era "em aberto":

![Screenshot 2021-08-24 at 14-40-23 ecom-bling – Cloud Firestore – Console do Firebase](https://user-images.githubusercontent.com/10326572/130663958-dd4f3037-4d05-4fde-998d-73ba480851c7.png)

O último callback do Bling que encontrei pra essa loja e esse pedido de fato foi o das 10:05:

![Screenshot 2021-08-24 at 14-43-42 ecom-bling – Console do Firebase](https://user-images.githubusercontent.com/10326572/130664512-be311fdf-c227-4715-9f19-5cdf71326290.png)

Nesse momento o pedido foi enfileirado (como você viu nos logs) e [lido no Bling](https://github.com/ecomplus/app-bling-erp/blob/master/functions/lib/integration/import-order.js#L21-L29), o retorno do Bling então é [salvo temporariamente no Firestore](https://github.com/ecomplus/app-bling-erp/blob/master/functions/lib/integration/import-order.js#L89-L93) como mostrei no primeiro print, nesse momento o Bling retornou que o pedido estava em aberto, por isso não foi alterado na plataforma.

**Comment by leomp12** [comment]
Sugiro que você leia diretamente a API do Bling para ver o status do pedido lá nesse momento, se ele estiver com outro status tente verificar o horário da alteração.

Se o horário da alteração for depois das 10:05 parece que não recebemos o último callback, se o alteração foi de fato às 10:05 eu acho que tinha algum problema na API deles, talvez só um cache na leitura, fato é que eles retornaram nessa ocasião que o pedido estava _em aberto_ (nas palavras do próprio Bling).

> Como a gente [só pega isso da resposta deles](https://github.com/ecomplus/app-bling-erp/blob/master/functions/lib/integration/import-order.js#L32-L34), não tem como brotar um _em aberto_ no doc do Firestore se eles não retornarem exatamente isso.

**Comment by leomp12** [comment]
> Vou manter o issue pro caso de você ter mais alguma informação ou dúvida, se não acho que ele pode ser fechado, até então me parece que o app executou o que deveria executar com os dados que recebeu...

**Comment by leomp12** [comment]
Só pra constar, alguns pedidos hoje não foram importados depois do commit de madrugada, dei esse fix agora e tô acompanhando.

**Comment by matheusgnreis** [comment]
Beleza, valeu

**Comment by leomp12** [comment]
https://github.com/ecomplus/app-bling-erp/issues/62
