### ISSUE TITLE
Erro de callback de notas fiscais

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/app-bling-erp#6]
O callback de situação de nota não foi concluído corretamente.

Dados enviados:

{“retorno”:{“notasfiscais”:[{“notafiscal”:{“serie”:“2”,“numero”:“000293”,“loja”:“203497102”,“numeroPedidoLoja”:“5545”,“tipo”:“S”,“situacao”:“Emitida DANFE”,“cliente”:{“nome”:“Ricardo Gandolfi”,“cnpj”:“xxxxxxxxxxx”,“ie”:"",“rg”:"",“endereco”:“Rua S\u00e3o Pedro”,“numero”:“637”,“complemento”:“Ap 51",“cidade”:“Curitiba”,“bairro”:“Cabral”,“cep”:“80.035-020”,“uf”:“PR”,“email”:"ricogandolfi@xxxxxx.com.br”,“fone”:“xxxx1823606”},“contato”:“Ricardo Gandolfi”,“cnpj”:“xxxxxxxxxxx”,“vendedor”:"",“dataEmissao”:“2020-12-17 13:45:38”,“valorNota”:“96.75”,“chaveAcesso”:“43201206051394000193550020000002931155433452”,“xml”:“https://www.bling.com.br/b/relatorios/nfe.xml.php?s%26chaveAcesso=43201206051394000193550020000002931155433452",“linkDanfe”:“https://www.bling.com.br/b/doc.view.php?id=b0c37f559c68a45e6c1a87e33457928d”,“codigosRastreamento”:{“codigoRastreamento”:“OM804811292BR”},“cfops”:[“6108”],“tipoIntegracao”:“Api”,“transporte”:{“volumes”:[{“volume”:{“id”:“10615541050”,“idServico”:“10299909884”,“servico”:"SEDEX CONTRATO AG”,“codigoServico”:“03220”,“codigoRastreamento”:“OM804811292BR”,“valorFretePrevisto”:“27.82”,“remessa”:null,“dataSaida”:"",“prazoEntregaPrevisto”:"",“valorDeclarado”:“0.00”,“avisoRecebimento”:false,“maoPropria”:false,“dimensoes”:{“peso”:“0.056”,“altura”:“0”,“largura”:“0”,“comprimento”:“0”,“diametro”:“0”},“urlRastreamento”:“www2.correios.com.br/sistemas/rastreamento?objetos=OMOM804811292BRBR"}}],“servico_correios”:"SEDEX CONTRATO AG”,“enderecoEntrega”:{“nome”:“Ricardo Gandolfi”,“endereco”:“Rua S\u00e3o Pedro”,“numero”:“637”,“complemento”:“Ap 51”,“cidade”:“Curitiba”,“bairro”:“Cabral”,“cep”:“80.035-020”,“uf”:“PR”}}}}]}}

**Comment by leomp12** [comment]
Como comentei na comunidade, esse callback de notas fiscais na verdade pode ser desabilitado, só trata alteração de situação.
De fato atualmente se o corpo recebido não tiver `estoques` nem `pedidos` nada vai acontecer.
